### ISSUE TITLE
Impossible to ask for no protections.

### ISSUE THREAD

**Issue by CodeMan99** [jscrambler/javascript-jscrambler#24]
I need to send a file with no protections so that my annotations can be applied. However, it is impossible to send [no parameters](https://github.com/jscrambler/javascript-jscrambler/blob/50f515e6066e9fedc6e5fea42014d6aa53629798/src/lib/index.js#L224-L227).

**Comment by CMatias** [comment]
Hi. That is indeed one use case which is not available.

While we work on a fix, could you perform your protections resorting to the `whitespaceRemoval` transformation?

**Comment by CodeMan99** [comment]
I was told that part of the problem was the change in block size. I would think `assertionsRemoval` would be a better hack.

On a similar token, I noticed an error in your documentation. The assertions removal rule stats you can use a regular expression, but in the same lines I already link the params are stringified. `JSON.stringify(/anything/)` simply returns an empty object.

**Comment by CMatias** [comment]
@CodeMan99 were you able to find a workaround? We've registered your findings as internal issues and will address them shortly.

**Comment by CodeMan99** [comment]
Closing as my goal seemed to be incorrect after further discussions with support via email.
