### ISSUE TITLE
No working examples in Readme

### ISSUE THREAD

**Issue by Wambosa** [jscrambler/javascript-jscrambler#3]
Your Readme provides false and misleading information.

If there are additional requirements other than nodejs and a jscrambler account. Then please specify.

npm install javascript-jscrambler failed with a 404.
npm install https://github.com/jscrambler/javascript-jscrambler is the way to go.

I see that your example code using the ```import``` keyword. This requires a transpiler and I am unable to figure out how to use this library as a result since i use vanilla nodejs.

Do i need to build your source code before i am able to use it? If so, then how does someone go about doing that?

**Comment by Wambosa** [comment]
here is a **working** example once you get past the npm install issue.

```javascript
/*
first: npm install https://github.com/jscrambler/javascript-jscrambler
then: the package to require will be named 'jscrambler'
warn: you cannot require this package normally because babel is retarded
note: that application ID, security keys need to be supplied by your account
note: version 4 of the jScramble API
*/

"use strict";

var jScrambler = requirejScrambler();

function requirejScrambler(){
    var _javascriptJscrambler = require('jscrambler');
    var _javascriptJscrambler2 = _interopRequireDefault(_javascriptJscrambler);
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
    return _javascriptJscrambler2.default;
}

jScrambler.protectAndDownload({
    "host": 'api4.jscrambler.com',
    "port": 443,
    "filesSrc": ["www/js/init/Shim.js", "www/js/init/Device.js", "www/js/init/Main.js"],
    "filesDest": "scrambled_app_folder",
    "keys": {
        "accessKey": "XXXXX",
        "secretKey": "SSSSS"
    },
    "applicationId": "AAAAA",
    "params": [{"name": "whitespaceRemoval"}, 
        {"name": "deadCodeInjection"},
        {"name": "functionOutlining"}, 
        {"name": "functionReordering"}, 
        {"name": "booleanToAnything"}, 
        {"name": "dotToBracketNotation"}, 
        {"name": "identifiersRenaming"}, 
        {"name": "propertyKeysObfuscation"}, 
        {"name": "numberToString"}, 
        {"name": "propertyKeysReordering"}, 
        {"name": "regexObfuscation"}, 
        {"name": "commaOperatorUnfolding"}, 
        {"name": "charToTernaryOperator"}, 
        {"name": "stringConcealing"}, 
        {"name": "stringEncoding"}, 
        {"name": "stringSplitting"}, 
        {"name": "variableGrouping"}, 
        {"name": "selfDefending"
    }],
    "areSubscribersOrdered": false,
    "applicationTypes": {
        "webBrowserApp": false,
        "desktopApp": false,
        "serverApp": false,
        "hybridMobileApp": true,
        "javascriptNativeApp": false,
        "html5GameApp": false
    },
    "languageSpecifications": {
        "es5": true,
        "es6": false,
        "es7": false
    }
}).then(function(){
    console.log("promises are awesome!");
}).catch(function(){
    console.log("await is for .NET!");
});;`

**Comment by CMatias** [comment]
Hi @Wambosa , sorry for not updating this, you'll find that the problem with the README file is now fixed. 

This issue will stay open while we provide a working example using es5.
For now, please check if you can simplify this:

```
var jScrambler = requirejScrambler();

function requirejScrambler(){
    var _javascriptJscrambler = require('jscrambler');
    var _javascriptJscrambler2 = _interopRequireDefault(_javascriptJscrambler);
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
    return _javascriptJscrambler2.default;
}
```

With this:

```
var jscrambler = require('jscrambler').default;
```

**Comment by joaosamouco** [comment]
See: #5

**Comment by ankurin1991** [comment]
I installed the API using the npm install jscrambler command. Now I made a .js file including the above code. I am getting a few errors.
Uncaught TypeError: jScrambler.protectAndDownload is not a function
Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by CMatias** [comment]
`require` is a node.js built-in function. Node makes use of it for its module loading (CommonJS). You have to run your script in node in order for it to be successful, it will not work in a browser. Require.js is a total different subject. It is not a drop-in replacement for node's `require`.

**Comment by ankurin1991** [comment]
Ok. So how do I move forward with this as I have never worked on Node.js.
I need to use the JScrambler API to integrate with my code.
Can you help me the steps I need to follow.
Currently what I did is installed jscrambler in my code location using 'npm install jscrambler' command.

What do I need to do next ?
Thanks

**Comment by CMatias** [comment]
If you have `npm` installed that means you have node.js installed. You can just copy and paste our README example into a javascript file (and replace your keys and app Id). You then just have to run `node jscrambler.js`.

**Comment by Wambosa** [comment]
@ankurin1991,

you can use the [jscrambler api](https://jscrambler.com/en/help/webapi/documentation), but be warned that it can expose your key because clientside javascript can run on machines outside of your control. where guys like me know how to look for those keys in your public source.

The typical approach is to create an api endpoint in your own backend systems that either 
A. use this library with node js
B. use the rest API and curl, bash, other

Then have your frontend code hit your own endpoint so that your key is not exposed

**Comment by CMatias** [comment]
@Wambosa I think that the use case you've described might be a little too advanced up to this point. And the documentation you've linked is outdated. Our current documentation [is here](https://docs.jscrambler.com/code-integrity/documentation/api/clients).

We need to know more about @ankurin1991's use case before diving deep into explanations.

**Comment by Wambosa** [comment]
ahh! i update the link. 

and those are pretty general use cases to provoke more questions and brain storming. sounds like he is trying to install the npm module then run the test on clientside js.

**Comment by ankurin1991** [comment]
I am geetin this error on using "node filename.js"

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: path must be a string
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ankur\Documents\Workshop\Chrome_Extension\JScrambler_obfuscation.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

**Comment by CMatias** [comment]
I'm sorry but this is not the place for us to help you debug your application. If you find any issues with our platform don't hesitate in contacting us (support@jscrambler.com). If there's any issue with our CLI/npm package then please open an issue here on github.
